service: notes-staging

servers:
  web:
    - <%= `bin/rails credentials:fetch -e staging kamal.server` %>

proxy:
  host: <%= `bin/rails credentials:fetch -e staging kamal.proxy_host` %>

ssh:
  user: <%= `bin/rails credentials:fetch -e staging kamal.ssh_user` %>

env:
  clear:
    RAILS_ENV: staging

volumes:
  - notes_staging_storage:/rails/storage
