service: notes-production

servers:
  web:
    - <%= `bin/rails credentials:fetch -e production kamal.server` %>

proxy:
  host: <%= `bin/rails credentials:fetch -e production kamal.proxy_host` %>

env:
  clear:
    RAILS_ENV: production

volumes:
  - notes_production_storage:/rails/storage
