require_destination: true

proxy:
  ssl: true

registry:
  server: localhost:5555

env:
  # NOTE: no need for ANY background jobs atm
  # clear:
  #   SOLID_QUEUE_IN_PUMA: true
  secret:
    - RAILS_MASTER_KEY

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "sh"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

asset_path: /rails/public/assets

builder:
  arch: amd64
